
[theme]
	title_font = 0
	background_color = "79,0,0,0"
	artist_font = 0
	title_color = "255,29,185,84"
	artist_color = "255,255,255,255"
	hide_image = false
	border_color = "255,1,165,82"

	[theme.controls]
		color = "255,255,255,255"
		selected_hover_color = "255,0,212,105"
		hover_color = "255,150,150,150"
		selected_color = "255,1,165,82"

	[theme.progress_bar]
		background_color = "255,25,20,20"
		color = "255,29,185,84"
		radius = 0.0
		number_color = "255,255,255,255"
		font = 0

	[theme.icons]
		play = "https://i.imgur.com/gGwLcTB.png"
		next = "https://i.imgur.com/J26CYIy.png"
		settings = "https://i.imgur.com/Ln0Ca9a.png"
		show_repeat_button = true
		show_external_link_button = true
		previous = "https://i.imgur.com/6NZCT1x.png"
		show_previous_button = true
		position_editor = "https://i.imgur.com/2uxli0V.png"
		show_next_button = true
		show_volume_control_button = true
		show_position_editor_button = true
		pause = "https://i.imgur.com/gertwAK.png"
		external_link = "https://i.imgur.com/eImse0e.png"
		volume_control = "https://i.imgur.com/C55dvVY.png"
		repeat = "https://i.imgur.com/2l7Wvfi.png"
		"show_play/pause_toggle" = true
		shuffle = "https://i.imgur.com/pdaYDPL.png"
		show_settings_button = true
		show_shuffle_button = true

