
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				husk = true
				bat = true
				hoglin = true
				rabbit = true
				firework_rocket = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wandering_trader = true
				vex = true
				goat = true
				horse = true
				vindicator = true
				phantom = true
				minecart = true
				leash_knot = true
				evoker = true
				glow_squid = true
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				endermite = true
				cat = true
				zombie = true
				ender_pearl = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				wolf = true
				skeleton_horse = true
				zombie_villager = true
				boat = true
				strider = true
				hopper_minecart = true
				painting = true
				witch = true
				cod = true
				spider = true

